[gui]
    title = "Unisci e dividi PDF"
    icon_img = "pdf_file.svg"

[select_gui]
    join_msg = "Unisci PDF"
    join_img = "join_icon.svg"
    split_msg = "Dividi PDF"
    split_img = "split_icon.svg"
    background_color = "#fffffc"

[generic_action_gui]
    action_btn = "VAI"
    action_color = "green"
    cancel_btn = "Annulla"
    cancel_color = "#9DA4C4"
    restart_btn = "Ricomincia"
    restart_color = "#DC851F"

[split_pdf_gui]
    background_color = "#caffbf"
    empty_msg = "Sposta qui il PDF da dividere"
    empty_img = "empty.svg"
#    empty_img = "new.svg"
    drag_and_drop_msg = "Lascia qui il file"
    drag_and_drop_img = "add_file_2.svg"
    ready_msg = "File selezionato, dividiamo?"
    ready_img = "pdf_file_2.svg"
    done_msg = "PDF diviso"
    done_img = "done.svg"
    invalid_msg = "File non supportato, scegli un PDF"
    invalid_img = "wrong_file.svg"

[join_pdf_gui]
    background_color = "#e2eafc"
    empty_msg = "Sposta qui i PDF da unire"
    empty_img = "empty.svg"
    full_img = "full_dir.svg"
    drag_and_drop_msg = "Lascia qui il file"
    drag_and_drop_img = "add_file_2.svg"
    done_msg = "PDF creato"
    done_img = "done.svg"
